### ISSUE TITLE
null pointer exception in RunLineMarkerProvider

### ISSUE THREAD

**Issue by jportway** [zio/zio-intellij#133]
During querying provider Run line marker (class com.intellij.execution.lineMarker.RunLineMarkerProvider)

```
java.lang.NullPointerException
	at zio.intellij.testsupport.package$testName$$anonfun$unapply$1.applyOrElse(package.scala:33)
	at zio.intellij.testsupport.package$testName$$anonfun$unapply$1.applyOrElse(package.scala:32)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
	at scala.Option.collect(Option.scala:282)
	at zio.intellij.testsupport.package$testName$.unapply(package.scala:32)
	at zio.intellij.testsupport.ZTestRunLineMarkerProvider.buildUrl(ZTestRunLineMarkerProvider.scala:44)
	at zio.intellij.testsupport.ZTestRunLineMarkerProvider.buildInfo$1(ZTestRunLineMarkerProvider.scala:29)
	at zio.intellij.testsupport.ZTestRunLineMarkerProvider.getInfo(ZTestRunLineMarkerProvider.scala:35)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:50)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:163)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:88)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

This was the code being indexed at the time (note the quotes and brackets are not closed on the "suite" method) : 

```
package org.stain.zkm
import zio._
import zio.console._
import zio.test._
import zio.test.Assertion._
import zio.test.environment._

object PDFConversionTest extends DefaultRunnableSpec {
  override def spec: ZSpec[_root_.zio.test.environment.TestEnvironment, Any] = suite("PDF{
    

  }
}
```

**Comment by hmemcpy** [comment]
This is very helpful, thank you for the report! Will look into it!
