### ISSUE TITLE
Error downloading plugin for latest Intellij CE EAP

### ISSUE THREAD

**Issue by kpbochenek** [zio/zio-intellij#270]
```
11:45 AM	Plugin error: Plugin 'ZIO for IntelliJ' (version '2021.1.7.0') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IC-212.3116.43
```

```
2021-05-28 11:44:38,749 [   6717]   WARN - Settings.impl.PluginDownloader - Request failed with status code 404
com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 404. Status=404, Url=https://plugins.jetbrains.com/pluginManager/?uuid=28052135d16dd37-2145-4eb0-bad8-280db139a9d6&id=zio.intellij.zio-intellij&build=IC-212.3116.43
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:657)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:631)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:356)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:364)
       ...
```

On a freshly downloaded Intellij for linux EAP version (CommunityEdition)

**Comment by hmemcpy** [comment]
Thanks, unfortunately the plugin is not available yet for IntelliJ 2021.2. An [early access](https://plugins.jetbrains.com/plugin/13820-zio-for-intellij/early-access-program-eap) build should be available soon. I'll update this issue when it's available.

**Comment by kpbochenek** [comment]
Thanks! :+1:

**Comment by hmemcpy** [comment]
Good news, it was just approved! Please check for updates after configuring the early access URL, and you should be able to install it in the 2021.2 EAP! https://plugins.jetbrains.com/plugin/13820-zio-for-intellij/versions/EAP/121089
