### ISSUE TITLE
Run all tests in package not supported

### ISSUE THREAD

**Issue by loathwine** [zio/zio-intellij#293]
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
com.intellij.openapi.util.InvalidDataException: Test configuration kind 'All in package' is not supported.
	at zio.intellij.testsupport.ZTestRunConfiguration.fromTestConfiguration(ZTestRunConfiguration.scala:44)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runnerInfo$2(ZTestRunConfiguration.scala:52)
	at scala.Option.getOrElse(Option.scala:201)
	at zio.intellij.testsupport.ZTestRunConfiguration.zio$intellij$testsupport$ZTestRunConfiguration$$runnerInfo(ZTestRunConfiguration.scala:52)
	at zio.intellij.testsupport.ZTestRunConfiguration$ZioTestCommandLineState.<init>(ZTestRunConfiguration.scala:82)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runStateProvider$1(ZTestRunConfiguration.scala:59)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration.getState(AbstractTestRunConfiguration.scala:190)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:222)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:96)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:731)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$executeConfiguration(ExecutionManagerImpl.kt:69)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:669)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:69)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:577)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Extra details:
ZIO Test right click test package and 'Run ZIO Tests in scala'
### Additional information:
<details>

ZIO plugin version: 2021.1.10.1
Scala plugin version: 2021.1.384
ZIO version(s): 1.0.9
Scala version(s): 2.13.1
sbt version: 1.3.8
IntelliJ version: IntelliJ IDEA 2021.1.2
Build #IC-211.7442.40
Java version: 11.0.11+9-b1341.57
Operating System: amd64 Linux (5.4.0-77-generic, amd64)
JVM version: Dynamic Code Evolution 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Looks like the error reporter is working :))

Thanks, unfortunately this feature is not implemented yet, but I'll try adding it...

**Comment by hmemcpy** [comment]
Relates to #26

**Comment by leszekgruchala** [comment]
Would be very useful to me too as I have a multimodule sbt project.

**Comment by i-am-the-slime** [comment]
Is there really no workaround to run more than one test with this?

**Comment by myazinn** [comment]
fixed in 2026.1.2.0 (compatible with IDEA 2026.1)
