### ISSUE TITLE
IncorrectOperationException in LambdaUtils

### ISSUE THREAD

**Issue by timaliberdov** [zio/zio-intellij#296]
Example code that causes exception:

```scala
trait Redis {
  def read: UIO[Unit]
  def read(n: Int): UIO[Unit]
}
type RedisService = Has[Redis]

ZIO.service[Redis].flatMap { redis => }
```

<details>
<summary>Stack trace</summary>

```
com.intellij.util.IncorrectOperationException: Must not change PSI outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:270)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:625)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:162)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:455)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:196)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.replace(LeafPsiElement.java:198)
	at zio.intellij.utils.LambdaUtils$$anonfun$replaceWithUnderscore$2.applyOrElse(LambdaUtils.scala:21)
	at zio.intellij.utils.LambdaUtils$$anonfun$replaceWithUnderscore$2.applyOrElse(LambdaUtils.scala:18)
	at scala.collection.IterableOnceOps.collectFirst(IterableOnce.scala:1086)
	at scala.collection.IterableOnceOps.collectFirst$(IterableOnce.scala:1078)
	at scala.collection.AbstractIterable.collectFirst(Iterable.scala:920)
	at zio.intellij.utils.LambdaUtils$.replaceWithUnderscore(LambdaUtils.scala:18)
	at zio.intellij.utils.LambdaUtils$.$anonfun$lambdaToUnderscore$1(LambdaUtils.scala:14)
	at scala.util.Either.fold(Either.scala:190)
	at zio.intellij.utils.LambdaUtils$.lambdaToUnderscore(LambdaUtils.scala:14)
	at zio.intellij.inspections.simplifications.ServiceWithSimplificationType$.replacement(SimplifyServiceWithInspection.scala:32)
	at zio.intellij.inspections.simplifications.ServiceWithSimplificationType$.getSimplification(SimplifyServiceWithInspection.scala:63)
	at zio.intellij.inspections.ZInspection.$anonfun$simplifications$4(ZInspection.scala:44)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
	at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
	at zio.intellij.inspections.ZInspection.zio$intellij$inspections$ZInspection$$simplifications(ZInspection.scala:44)
	at zio.intellij.inspections.ZInspection$$anonfun$actionFor$1.applyOrElse(ZInspection.scala:31)
	at zio.intellij.inspections.ZInspection$$anonfun$actionFor$1.applyOrElse(ZInspection.scala:29)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at org.jetbrains.plugins.scala.codeInspection.AbstractInspection$$anon$1.visitElement(AbstractInspection.scala:24)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementImpl.org$jetbrains$plugins$scala$lang$psi$api$ScalaPsiElement$$super$accept(ScalaPsiElementImpl.scala:20)
	at org.jetbrains.plugins.scala.lang.psi.api.ScalaPsiElement.accept(ScalaPsiElement.scala:109)
	at org.jetbrains.plugins.scala.lang.psi.api.ScalaPsiElement.accept$(ScalaPsiElement.scala:107)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementImpl.accept(ScalaPsiElementImpl.scala:20)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:279)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:161)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:153)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:277)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:277)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

Couldn't submit using error reporter. See #295

**Comment by hmemcpy** [comment]
serviceWith makes me cri
