### ISSUE TITLE
An unhandled exception occurred in the plugin

### ISSUE THREAD

**Issue by mtk** [zio/zio-intellij#322]
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
com.intellij.diagnostic.PluginException: Short name 'SimplifyUnitInspection' is not unique
class 'zio.intellij.inspections.simplifications.SimplifyUnitInspection' in PluginDescriptor(name=ZIO for IntelliJ, id=zio.intellij.zio-intellij, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2021.2/zio-intellij, version=2021.2.12.0, package=null)
and class 'zio.intellij.inspections.simplifications.SimplifyUnitInspection' in PluginDescriptor(name=ZIO for IntelliJ, id=zio.intellij.zio-intellij, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2021.2/zio-intellij, version=2021.2.11.1, package=null)
conflict
	at com.intellij.codeInspection.ex.InspectionToolRegistrarKt.checkForDuplicateShortName(InspectionToolRegistrar.kt:176)
	at com.intellij.codeInspection.ex.InspectionToolRegistrarKt.registerInspection(InspectionToolRegistrar.kt:135)
	at com.intellij.codeInspection.ex.InspectionToolRegistrarKt.access$registerInspection(InspectionToolRegistrar.kt:1)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar$registerInspections$1.extensionAdded(InspectionToolRegistrar.kt:72)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar$registerInspections$1.extensionAdded(InspectionToolRegistrar.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:785)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$registerExtensions$17(ExtensionPointImpl.java:985)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$1.run(DynamicPlugins.kt:820)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:808)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:790)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:392)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.tryInstallWithoutRestart(PluginDownloader.java:351)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$4.lambda$run$0(PluginUpdateDialog.java:198)
	at com.intellij.openapi.updateSettings.impl.UpdateInstaller.installDownloadedPluginUpdates(UpdateInstaller.kt:113)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$4.lambda$run$1(PluginUpdateDialog.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
### Additional information:
<details>

ZIO plugin version: 2021.2.12.0
Scala plugin version: 2021.2.17
ZIO version(s): 1.0.7
Scala version(s): 2.13.5
sbt version: 1.5.5
IntelliJ version: IntelliJ IDEA 2021.2.1 RC
Build #IU-212.5080.39
Java version: 11.0.11+9-b1504.16
Operating System: amd64 Linux (5.13.12-200.fc34.x86_64, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Oh wow, this I did not expect... it looks as if it, somehow, two versions of the plugin are loaded. Did you just upgrade your IntelliJ? Maybe it dun goofed when copying the existing profile to the new version...

Could you please try removing the ZIO plugin, restart IntelliJ, then install it again from the marketplace? Let's hope it's a fluke...

**Comment by hmemcpy** [comment]
Just in case, I built a new version of the plugin, ensuring workspaces were clean before compiling. Let's hope this problem doesn't come back.

**Comment by mtk** [comment]
yes, this happened immediately after an upgrade.  let me restart and see if
it reoccurs.

**Comment by mtk** [comment]
absolutely nothing after a restart.  must be a complexity-related heisenbug
event.  sorry for the fire alarm.

**Comment by hmemcpy** [comment]
Cool :) Thanks for the update.
Let me know if it comes back...
