### ISSUE TITLE
scalaJS targets are not supported by the test runner

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#35]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
  at org.portablescala.reflect.Reflect$.lookupLoadableModuleClass(Reflect.scala:23)
  at org.portablescala.reflect.Reflect$.lookupLoadableModuleClass(Reflect.scala:41)
  at zio.intellij.testsupport.runner.ZTestRunner$.createSpec(ZTestRunner.scala:26)
  at zio.intellij.testsupport.runner.ZTestRunner$.run(ZTestRunner.scala:35)
  at zio.intellij.testsupport.runner.ZTestRunnerHost.main(ZTestRunnerHost.java:5)
Caused by: java.lang.ClassCastException: scala.scalajs.js.Object cannot be cast to scala.scalajs.js.Dictionary
  at scala.scalajs.js.Dictionary$.empty(Dictionary.scala:83)
  at scala.scalajs.reflect.Reflect$.<init>(Reflect.scala:72)
  at scala.scalajs.reflect.Reflect$.<clinit>(Reflect.scala)
  ... 5 more
```

**Comment by hmemcpy** [comment]
Need to make sure the run configuration prefers the JVM modules

**Comment by hmemcpy** [comment]
I'm closing this. The test runner is compiling against scalajs, but I've never seen it in the wild... if there are problems - please open an issue!
