### ISSUE TITLE
An unhandled exception occurred in the plugin

### ISSUE THREAD

**Issue by erikvanoosten** [zio/zio-intellij#369]
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
com.intellij.openapi.util.InvalidDataException: Test configuration kind 'All in package' is not supported.
	at zio.intellij.testsupport.ZTestRunConfiguration.fromTestConfiguration(ZTestRunConfiguration.scala:45)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runnerInfo$4(ZTestRunConfiguration.scala:52)
	at scala.Option.getOrElse(Option.scala:201)
	at zio.intellij.testsupport.ZTestRunConfiguration.zio$intellij$testsupport$ZTestRunConfiguration$$runnerInfo(ZTestRunConfiguration.scala:52)
	at zio.intellij.testsupport.ZTestRunConfiguration$ZioTestCommandLineState.<init>(ZTestRunConfiguration.scala:85)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runStateProvider$1(ZTestRunConfiguration.scala:59)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration.getState(AbstractTestRunConfiguration.scala:193)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:216)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:96)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:741)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$executeConfiguration(ExecutionManagerImpl.kt:72)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:677)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:596)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

### Extra details:
Steps to reproduce:
 - in project view open context menu on /src/test/scala
 - select "Run 'ZIO Tests in scala'"
### Additional information:
<details>

ZIO plugin version: 2022.1.16.0
Scala plugin version: 2022.1.13
ZIO version(s): 1.0.14
Scala version(s): 2.12.15
sbt version: 1.6.2
IntelliJ version: IntelliJ IDEA 2022.1
Build #IC-221.5080.210
Java version: 11.0.14.1+1-b2043.25
Operating System: x86_64 Mac OS X (11.6.5, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by myazinn** [comment]
fixed long ago but we forgot to close it :)
