### ISSUE TITLE
Unhandled exception: com.intellij.openapi.util.InvalidDataException: Test configuration kind 'All in package' is not supported.

### ISSUE THREAD

**Issue by xvThomas** [zio/zio-intellij#377]
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
com.intellij.openapi.util.InvalidDataException: Test configuration kind 'All in package' is not supported.
	at zio.intellij.testsupport.ZTestRunConfiguration.fromTestConfiguration(ZTestRunConfiguration.scala:52)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runnerInfo$4(ZTestRunConfiguration.scala:59)
	at scala.Option.getOrElse(Option.scala:201)
	at zio.intellij.testsupport.ZTestRunConfiguration.zio$intellij$testsupport$ZTestRunConfiguration$$runnerInfo(ZTestRunConfiguration.scala:59)
	at zio.intellij.testsupport.ZTestRunConfiguration$ZioTestCommandLineState.<init>(ZTestRunConfiguration.scala:92)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runStateProvider$1(ZTestRunConfiguration.scala:66)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration.getState(AbstractTestRunConfiguration.scala:193)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:213)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:97)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:741)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$executeConfiguration(ExecutionManagerImpl.kt:72)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:677)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:596)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```
### Additional information:
<details>

ZIO plugin version: 2022.2.20.0
Scala plugin version: 2022.2.17
ZIO version(s): 2.0.2
Scala version(s): 2.13.8
sbt version: 1.7.2
IntelliJ version: IntelliJ IDEA 2022.2.3
Build #IU-222.4345.14
Java version: 17.0.4.1+7-b469.62
Operating System: aarch64 Mac OS X (12.6, aarch64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by longliveenduro** [comment]
Same problem for me here
