### ISSUE TITLE
Unhandled exception: java.lang.NoSuchMethodError: 'org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementFactory$.createExpressionFromText(java.lang.String, com.intellij.psi.PsiElement)'

### ISSUE THREAD

**Issue by bbdimitriu** [zio/zio-intellij#384]
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
java.lang.NoSuchMethodError: 'org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementFactory$.createExpressionFromText(java.lang.String, com.intellij.psi.PsiElement)'
	at zio.intellij.inspections.simplifications.ChainToForSimplificationType$.getSimplification(SimplifyChainToForInspection.scala:40)
	at zio.intellij.inspections.ZInspection.$anonfun$simplifications$4(ZInspection.scala:45)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
	at zio.intellij.inspections.ZInspection.simplifications(ZInspection.scala:45)
	at zio.intellij.inspections.ZInspection.zio$intellij$inspections$ZInspection$$$anonfun$buildVisitor$1(ZInspection.scala:31)
	at zio.intellij.inspections.ZInspection$$anonfun$buildVisitor$3.visitPsiElement(ZInspection.scala:29)
	at org.jetbrains.plugins.scala.codeInspection.package$PsiElementVisitorSimple.visitElement(package.scala:102)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementImpl.org$jetbrains$plugins$scala$lang$psi$api$ScalaPsiElement$$super$accept(ScalaPsiElementImpl.scala:21)
	at org.jetbrains.plugins.scala.lang.psi.api.ScalaPsiElement.accept(ScalaPsiElement.scala:108)
	at org.jetbrains.plugins.scala.lang.psi.api.ScalaPsiElement.accept$(ScalaPsiElement.scala:106)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementImpl.accept(ScalaPsiElementImpl.scala:21)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInspection.InspectionEngine.lambda$inspectElements$8(InspectionEngine.java:282)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```
### Additional information:
<details>

ZIO plugin version: 2022.3.17.834
Scala plugin version: 2022.3.13
ZIO version(s): 2.0.2
Scala version(s): 3.2.1
sbt version: 1.6.2
IntelliJ version: IntelliJ IDEA 2022.3
Build #IU-223.7571.182
Java version: 17.0.5+1-b653.14
Operating System: aarch64 Mac OS X (13.0.1, aarch64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Oh no, thanks. I'll get it fixed!

**Comment by hmemcpy** [comment]
Do you maybe have a snippet of code where this error was triggered? Looks like it has something to do with analyzing chains of `*>`. If you can provide a tiny snippet it would be helpful to reproduce. Thanks!

**Comment by bbdimitriu** [comment]
Uh, apologies, I'm not sure I can provide any useful information here. I have refactored the code quite a bit since then and now I don't have any "*>". IntelliJ doesn't make it easy for me to get a good idea of when/where the problem occurred.
I had something like:
```
(for { 
....
} yield ()).catchAll(error => ZIO.logError(s"Record processing failed with: $error")) *> ZIO.succeed(record)
```

and at some other point something like:
```
(if (success) ZIO.logInfo("Success")
else ZIO.logWarning("Failure")) *> ZIO.succeed(record)
```

**Comment by hmemcpy** [comment]
Perfect. I'll try working at it! Thanks a lot!

**Comment by hmemcpy** [comment]
Unfortunately I couldn't reproduce this, I suspect this was possibly caused by some API change in between releases. If this happens again - please open another issue! 🙏

**Comment by bbdimitriu** [comment]
No problem. I haven't actually seen it happening since then. Thanks!
