### ISSUE TITLE
Problem running tests from IntelliJ in RC18

### ISSUE THREAD

**Issue by FloWi** [zio/zio-intellij#40]
In RC17 I was able to run the tests from within IntelliJ. I think in RC18 s.th. broke.

I get this error from the ZTestRunner.

```text
Exception in thread "main" java.lang.NoSuchMethodError: zio.test.TestRunner.unsafeRun$default$2()Lzio/test/TestLogger;
	at zio.intellij.testsupport.runner.ZTestRunner$.run(ZTestRunner.scala:37)
	at zio.intellij.testsupport.runner.ZTestRunnerHost.main(ZTestRunnerHost.java:5)
```
As discussed with @adamgfraser in https://github.com/zio/zio/issues/3014 it seems to be an issue with the IDEA plugin.

**Comment by holinov** [comment]
same problem here
