### ISSUE TITLE
Unhandled exception: com.intellij.openapi.util.InvalidDataException: Test configuration kind 'All in package' is not supported.

### ISSUE THREAD

**Issue by ghost** [zio/zio-intellij#457]
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
com.intellij.openapi.util.InvalidDataException: Test configuration kind 'All in package' is not supported.
	at zio.intellij.testsupport.ZTestRunConfiguration.fromTestConfiguration(ZTestRunConfiguration.scala:52)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runnerInfo$4(ZTestRunConfiguration.scala:59)
	at scala.Option.getOrElse(Option.scala:201)
	at zio.intellij.testsupport.ZTestRunConfiguration.zio$intellij$testsupport$ZTestRunConfiguration$$runnerInfo(ZTestRunConfiguration.scala:59)
	at zio.intellij.testsupport.ZTestRunConfiguration$ZioTestCommandLineState.<init>(ZTestRunConfiguration.scala:92)
	at zio.intellij.testsupport.ZTestRunConfiguration.$anonfun$runStateProvider$1(ZTestRunConfiguration.scala:66)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration.getState(AbstractTestRunConfiguration.scala:194)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:218)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:93)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:784)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$executeConfiguration(ExecutionManagerImpl.kt:78)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$1$2.invoke(ExecutionManagerImpl.kt:717)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$1$2.invoke(ExecutionManagerImpl.kt:713)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration$lambda$11$lambda$10(ExecutionManagerImpl.kt:713)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$7(NonBlockingReadActionImpl.java:708)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```
### Additional information:
<details>

ZIO plugin version: 2023.2.27.0
Scala plugin version: 2023.2.27
ZIO version(s): 1.0.8
Scala version(s): 2.12.13
sbt version: 1.4.9
IntelliJ version: IntelliJ IDEA 2023.2.2
Build #IU-232.9921.47
Java version: 17.0.8+7-b1000.22
Operating System: aarch64 Mac OS X (14.1.1, aarch64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by Kreinoee** [comment]
This looks to be a duplicate of #293
